name: langchain_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - langchain-openai
      - langchain-core
      - langchain_huggingface
      - python-dotenv
      - streamlit
      - langchain-community
      - langserve
      - fastapi
      - uvicorn
      - sse-starlette
      - bs4
      - pypdf
      - chromadb
      - faiss-cpu
      - groq
      - cassio
      - beautifulsoup4
      - langchain-groq
      - wikipedia
      - arxiv
      - langchainhub
      - sentence-transformers
      - PyPDF2
      - langchain-objectbox
      - langchain
      - ipykernel
